name: thousandbricks
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
#  firebase_messaging: ^7.0.0
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  provider: ^4.3.3
  cloud_firestore: any
  file_picker: ^1.9.0+1
  path: ^1.6.4
  flutter_local_notifications: ^1.4.4+4
  date_format: ^2.0.2
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true